#!/bin/sh

CONFARGS=""

if [ -n "$RAVEROOT" ]; then
  CONFARGS="--prefix=$RAVEROOT "
else
  CONFARGS="--prefix=/opt/rave "
fi

if [ -n "$HLDIR" ]; then
  CONFARGS="$CONFARGS --with-hlhdf=$HLDIR "
fi

if [ -n "$NUMPYDIR" ]; then
  CONFARGS="$CONFARGS --with-numpy=$NUMPYDIR "
fi

if [ -n "$CFLAGS" ]; then
  TEMPSTR=`echo "$CFLAGS" | sed -e "s/-DRAVE_MEMORY_DEBUG//g"`
  if [ "$CFLAGS" != "$TEMPSTR" ]; then
    CONFARGS="$CONFARGS --enable-debug-memory "
  fi
fi

if [ -n "$PROJ4ROOT" ]; then
  CONFARGS="$CONFARGS --with-legacy-proj=$PROJ4ROOT/include,$PROJ4ROOT/lib"
else
  PROJARG=
  if [ -n "$PROJ4INC" ]; then
    PROJARG="--with-legacy-proj=$PROJ4INC"
  fi
  if [ -n "$PROJ4LIB" ]; then
    if [ -n "$PROJARG" ]; then
      PROJARG="$PROJARG,$PROJ4LIB"
    else
      PROJARG="--with-legacy-proj=,$PROJ4LIB"
    fi
  fi
  CONFARGS="$CONFARGS $PROJARG"
fi

if [ -n "$PROJROOT" ]; then
  CONFARGS="$CONFARGS --with-proj=$PROJROOT/include,$PROJROOT/lib"
else
  PROJARG=
  if [ -n "$PROJINC" ]; then
    PROJARG="--with-proj=$PROJINC"
  fi
  if [ -n "$PROJLIB" ]; then
    if [ -n "$PROJARG" ]; then
      PROJARG="$PROJARG,$PROJLIB"
    else
      PROJARG="--with-proj=,$PROJLIB"
    fi
  fi
  CONFARGS="$CONFARGS $PROJARG"
fi


if [ -n "$EXPATARG" ]; then
  CONFARGS="$CONFARGS --with-expat=$EXPATARG"
fi

if [ -n "$ENABLEPY3SUPPORT" ]; then
  CONFARGS="$CONFARGS --enable-py3support"
fi

if [ -n "$BUFRARG" ]; then
  CONFARGS="$CONFARGS --with-bufr=$BUFRARG"
fi

if [ -n "$NETCDFARG" ]; then
  CONFARGS="$CONFARGS --with-netcdf=$NETCDFARG"
fi

echo "Running: ./configure $CONFARGS"

./configure $CONFARGS
