/**

    Copyright 2001 - 2010  Markus Peura,
    Finnish Meteorological Institute (First.Last@fmi.fi)


    This file is part of Rack.

    Rack is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Rack is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser Public License for more details.

    You should have received a copy of the GNU Lesser Public License
    along with Rack.  If not, see <http://www.gnu.org/licenses/>. */



/* This code is generated by ./fmi_radar_codes.sh - don't edit */
typedef enum {CLEAR, CUTOFF, BIOMET, SHIP, SUN, EMITTER, EMITTER2, CLUTTER, CLUTTER2, SPECK, DOPPLER, GROUND, METEOSAT, THRESH1, EMITTER3, DATA_MIN, DATA_MAX, NO_DATA} FmiRadarPGMCode;
