printf("RADAR IMAGE INPUT \n");
printf(" sweeps:\n");
printf("  sweep1.pgm [sweep2.pgm ... sweepN.pgm]\n");
printf(" target:\n");
printf("  target.pgm \n");
printf("INTERNAL IMAGES & DATA STRUCTURES:\n");
printf("  treats radar data as both sweeps and volumes\n");
printf("   volume     - input image:\n");
printf("   volume[0]  - input image (concatenated raw volume)\n");
printf("   volume[1]  - input image, 1st sweep (linked to volume[1])\n");
printf("   volume[2]  - input image, 2nd sweep (and so on)\n");
printf(" internal auxiliary images (linked like 'volume'):\n");
printf("  volume_filtered - resulting image\n");
printf("  prob            - 'current' probability \n");
printf("  master_prob     - master probability \n");
printf("  marked image, volume\n");
printf("  prob - probability for current sweep\n");
printf("SWEEP SELECTION (sweep to be processed/output, one (lowest) by default\n");
printf("  -sweep s\n");
printf(" -cappi <ALTITUDE>   compute intersection (output to current sweep)\n");
printf(" -cappi 500m\n");
printf("ROPO DETECTORS (or 'filters')\n");
printf(" <OPTIONS>  capital   letters <=> strict values\n");
printf(" <options>  lowercase letters <=> fuzzy  values\n");
printf(" -speck <MIN_DBZ> <max_a>  Threshold by min dBz, detect specks < A \n");
printf(" -speck  -20dBz     5pix     \n");
printf(" -specknorm_old <MIN_DBZ> <max_a> <max_n>  Threshold by min dBz, then detect specks, size A_max_range <=> size N*A A \n");
printf("               -20        5       16  \n");
printf(" -clutter <MIN_DBZ> <max_incomp>	 Remove specks under incompactness A\n");
printf("              -5         5 \n");
printf(" -clutter2 <MIN_DBZ> <max_smooth> Remove specks under smoothness\n");
printf("               -5           60\n");
printf(" -ground <-DBZ/1000m> <half_altitude> Remove ground echo by steepest-descent\n");
printf("            -5dbz            2500m \n");
printf(" -ground2 <-DBZ/1000m> <half_altitude> Remove ground echo by steepest-descent, normalized\n");
printf("            -5dbz            2500m \n");
printf(" -meteosat img.pgm <T_P50> <T_P75> <MIN DBZ> <min area> Remove hot large specks\n");
printf("                     -9'C    -7'C     30dbz     10pix \n");
printf(" -softcut  <max_dbz>     <r>     <r2>	 Remove insect band\n");
printf("           -10dbz    250km   100km\n");
printf(" -biomet  <dbz_max> <dbz_delta> <alt_max> <alt_delta>   Remove insect band\n");
printf("             -10dbz      5dBZ       5000m     1km\n");
printf(" -ship <min rel DBZ> <min A> Remove ships\n");
printf("           50           20 \n");
printf(" -emitter <MIN_DBZ> <LENGTH>   Filter unity-width emitter lines\n");
printf("            10dbz      4 \n");
printf(" -emitter0 <MIN_DBZ> <min_length> <max_width>   Filter emitter lines\n");
printf(" -emitter0  -20dBZ       8bins        2°           \n");
printf(" -emitter2 <MIN_DBZ> <LENGTH> <width> 	 Filter emitter lines\n");
printf("              -10dbz 4bins 2°\n");
printf("              -10dbz 3bins 3°\n");
printf(" -emitter2 <MIN_DBZ> <LENGTH> <width> 	 Filter emitter lines\n");
printf("               10        4        2 \n");
printf(" -sun      <MIN_DBZ>  <min_length> <max_thickness>      Remove sun \n");
printf("            -20dBZ        100           3\n");
printf(" -sun2   <MIN_DBZ>  <min_length> <max_thickness> <azimuth> <elevation>   Remove sun \n");
printf("           -20dBZ        100          3             45°        2°\n");
printf(" -doppler <filename> <WIDTH> <HEIGHT> <threshold>   Remove doppler anomalies\n");
printf(" -doppler file.pgm 1bins 1° 128   Remove doppler anomalies\n");
printf(" sampling\n");
printf("  -SVc x y     Volume dbz's, cartesian coords\n");
printf("  -SVp r phi   Volume dbz's, polar coords\n");
printf("ONLINE RESTORATION (sweep, affects the source image, unrecoverable)  \n");
printf(" -t <PROB>        (use -OO** and -Oo**  to extract images)\n");
printf("ONLINE DETECTION (sweep) (NEGATIVE FILTERING) \n");
printf(" -d <PROB>        (use -Of**  to extract images)\n");
printf("OFFLINE RESTORATION (results to separate image, repeatable)  \n");
printf(" -Ts <PROB>     (current sweep)\n");
printf(" -Tv <PROB>     (volume)\n");
printf("OUTPUT (applicable multiple times, in any stage of processing)\n");
printf(" -O<image><proj><format> filename[.p?m]\n");
printf("  <image>\n");
printf("     O    volume, original/online-filtered\n");
printf("     o    current sweep, original/online-filtered\n");
printf("     D    volume, detected (=negative filtered)\n");
printf("     d    current sweep, detected (=negative filtered)\n");
printf("     F    volume, offline-filtered\n");
printf("     f    current sweep, offline-filtered\n");
printf("     P    probability of anomalies (volume, cumulated by detectors this far)\n");
printf("     p    probability of anomalies (sweep,cumulated)\n");
printf("     A    probability of anomaly (volume, by latest detector)\n");
printf("     a    probability of anomaly (sweep, by latest detector)\n");
printf("     M    image with anomalies marked with EMIT,SHIP etc, vol\n");
printf("     m    image with anomalies marked with EMIT,SHIP etc, vol\n");
printf("  <proj>  image projection\n");
printf("     c    cartesian\n");
printf("     p    polar\n");
printf("     4    2x2 combo, ex:  -O*4* combo.ppm = (source,*)x(polar,cartesian)\n");
printf("     6    3x2 combo\n");
printf(" <format> image coloring and format\n");
printf("     t    gray, pgm (no LSB codes (threshold=16) black background)\n");
printf("     G    gray, pgm (black background)\n");
printf("     g    gray, pgm (white background)\n");
printf("     V    gray, pgm (printable media, white background)\n");
printf("     V    gray, pgm (printable media, inverted, white background)\n");
printf("     I    colored, IRIS-like, black background\n");
printf("     i    colored, IRIS-like\n");
printf("     r    colored (x<128=green, x>128=red), ppm\n");
printf("     M    gray, marked (colored background), DATA_MIN cutoff, ppm\n");
printf("     m    gray, marked, ppm\n");
printf("     h    gray, hdf5\n");
printf("DEBUGGING <0=nothing ... 5 everything> (dump info and intermed. res. images)\n");
printf(" -debug <n>  \n");
