###########################################################################
# Copyright (C) 2009 Swedish Meteorological and Hydrological Institute, SMHI,
#
# This file is part of RAVE.
#
# RAVE is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# RAVE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with RAVE.  If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------
# 
# For pytest directory, only clean functionality since rest is done from script
# @file
# @author Anders Henja (Swedish Meteorological and Hydrological Institute, SMHI)
# @date 2009-12-10
###########################################################################

.PHONY:clean
clean: ;
	 
.PHONY:distclean
distclean:
	@\rm -fr cartesian.h5
	@\rm -fr cartesian_cappi.h5
	@\rm -fr cartesian_pcappi.h5
	@\rm -fr cartesian_ppi.h5
	@\rm -fr ctop_polarscan.h5
	@\rm -fr ctop_polarvolume.h5
	@\rm -fr smurf.h5
	@\rm -fr swecomposite.h5
	@\rm -fr swecomposite_gmap.h5
	@\rm -fr swecomposite_ppi.h5
	@\rm -fr swecomposite_ppi_fromscan.h5
	@\rm -fr swecomposite_gmap_overlapping.h5
	@\rm -fr build
	@\rm -f *~
