#!/bin/sh

CONFARGS=""

if [ -n "$RAVEROOT" ]; then
  CONFARGS="--prefix=$RAVEROOT "
else
  CONFARGS="--prefix=/opt/rave "
fi

if [ -n "$HLDIR" ]; then
  CONFARGS="$CONFARGS --with-hlhdf=$HLDIR "
fi

if [ -n "$NUMPYDIR" ]; then
  CONFARGS="$CONFARGS --with-numpy=$NUMPYDIR "
fi

if [ -n "$CFLAGS" ]; then
  TEMPSTR=`echo "$CFLAGS" | sed -e "s/-DRAVE_MEMORY_DEBUG//g"`
  if [ "$CFLAGS" != "$TEMPSTR" ]; then
    CONFARGS="$CONFARGS --enable-debug-memory "
  fi
fi

if [ -n "$PROJ4ROOT" ]; then
  CONFARGS="$CONFARGS --with-proj=$PROJ4ROOT/include,$PROJ4ROOT/lib"
else
  PROJARG=
  if [ -n "$PROJ4INC" ]; then
    PROJARG="--with-proj=$PROJ4INC"
  fi
  if [ -n "$PROJ4LIB" ]; then
    if [ -n "$PROJARG" ]; then
      PROJARG="$PROJARG,$PROJ4LIB"
    else
      PROJARG="--with-proj=,$PROJ4LIB"
    fi
  fi
  CONFARGS="$CONFARGS $PROJARG"
fi

echo "Running: ./configure $CONFARGS"

./configure $CONFARGS
